### PR TITLE
Remove tilde (~) from list chars. Closes verbose/verb#70.

### PR DESCRIPTION
**Pull request by AndersDJohnson**
Remove tilde (~) from list chars, since not parts of specs:
- http://spec.commonmark.org/0.19/#list-items
- https://daringfireball.net/projects/markdown/syntax#list
- https://help.github.com/articles/markdown-basics/#lists

Also updates test cases to pass, and updates README via `verb`, which I needed to add to dev deps (at master version due to verbose/verb#62) to prevent an error building related to `apidocs` helper with `verb-cli@0.7.2`.

 Closes verbose/verb#70.

### CODE REVIEW

**Comment by AndersDJohnson** [comment]
The Travis build seems to be failing because it is trying to run `rake` as though this were a Ruby project - perhaps due to missing `.travis.yml` - see #2 for to fix that.

**Comment by jonschlinkert** [comment]
@adjohnson916 added you as a collab. feel free to merge!

**Comment by AndersDJohnson** [comment]
@jonschlinkert Thanks! Merged and tagged as v1.0.0 - but need npm maintainer to publish.

**Comment by jonschlinkert** [comment]
done! added you as npm maintainer. feel free to publish

**Comment by jonschlinkert** [comment]
@adjohnson916 looks like this was never published to npm. want me to do that?

**Comment by jonschlinkert** [comment]
I just noticed that you said this was tagged 1.0. I just published 0.1.3/0.1.4 but unpublished them and republished as 1.0.1 to sync up with the tag. all is good, but I'm curious why we tagged this as 1.0.

**Comment by AndersDJohnson** [comment]
@jonschlinkert I debated that internally. Semantic versioning is not always a science. Some might consider this a bug fix (patch or minor version), others a breaking change (major). Where there was doubt, I opted for a major bump, to allow selective opt-in, rather than force the update. Up to you if you prefer one or the other, I don't mind.

**Comment by AndersDJohnson** [comment]
@jonschlinkert Oops, looks like I hadn't bumped the version in package.json before tagging 1.0.0. Sorry if that caused any confusion.

**Comment by jonschlinkert** [comment]
no prob, thanks for sharing your thoughts on that, not important at all. what is important, though, is that I really appreciate the help and you write really nice code! so thank you again, I'd love to have you help out any time

**Comment by AndersDJohnson** [comment]
@jonschlinkert Thanks. Looks like maybe 1.0.1 didn't make it to the npm registry? I'm seeing 0.1.2 as the latest still. Want me to push it up?

**Comment by jonschlinkert** [comment]
yes that would be great, thanks!

**Comment by AndersDJohnson** [comment]
Published tag 1.0.1 to npm.

**Comment by AndersDJohnson** [comment]
@jonschlinkert I notice that you create tags without the "v" prefix - but `npm version` automatically creates tags with the "v" prefix. Do you have a preference for either syntax, and what tools if any are you using to bump?

**Pull request merged**
